export const SEND_REGISTER_EMAIL = "SEND_REGISTER_EMAIL";
export const END_REGISTER = "END_REGISTER";
export const LOGIN = "LOGIN";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_SOUNDS_BY_TYPE = "GET_SOUNDS_BY_TYPE";

export const CREATE_RESULT = "CREATE_RESULT";